const fs = require('fs');

const how_it_works_tr = {
  badge_flow: "Akış",
  hero_title: "Nasıl Çalışır?",
  hero_desc: "IARONE, ürün fotoğrafından başlayarak web ve artırılmış gerçeklikte kullanılabilecek satışa hazır 3D/AR varlıklar üretir. Marka yalnızca ürün görselini yükler; sistem arka planda 3D üretim, optimizasyon, kalite kontrol ve yayınlama süreçlerini tek akışta yönetir.",
  step1_title: "Ürün Fotoğrafını Yükle",
  step1_desc1: "Marka, ürün fotoğrafını IARONE paneline yükler. Ürün adı, kategori, isteğe bağlı ölçü bilgisi veya referans nesne gibi detaylar eklenebilir.",
  step1_desc2: "Bu adımda kullanıcının teknik bilgiye ihtiyacı yoktur. Blender, 3D modelleme veya AR entegrasyon bilgisi gerekmez.",
  step_highlights: "Öne Çıkanlar",
  step1_li1: "Ürün fotoğrafı yükleme",
  step1_li2: "Kategori seçimi",
  step1_li3: "Ölçü / referans bilgi ekleme",
  step1_li4: "Teknik bilgi gerektirmeyen başlangıç",
  step2_title: "AI ile 3D Model Üretimi Başlar",
  step2_desc1: "Yüklenen görsel, IARONE’un 3D üretim altyapısına aktarılır. Sistem, ürünün formunu, hacmini ve temel geometrisini analiz ederek 3D model üretim sürecini başlatır.",
  step2_desc2: "Bu aşamada amaç yalnızca bir 3D dosya oluşturmak değil; e-ticaret kullanımına uygun bir ürün varlığı üretmektir.",
  step2_li1: "Görselden 3D model üretimi",
  step2_li2: "Ürün formunun çıkarılması",
  step2_li3: "Geometri ve temel yüzey yapısının oluşturulması",
  step2_li4: "E-ticaret odaklı 3D üretim akışı",
  step3_title: "Model Web ve E-ticaret İçin Optimize Edilir",
  step3_desc1: "AI ile üretilen ham model doğrudan müşteriye verilmez. IARONE, modeli web sitelerinde daha hızlı açılabilecek, ürün sayfalarında daha rahat görüntülenebilecek ve mobil cihazlarda daha akıcı çalışabilecek hale getirir.",
  step3_desc2: "Bu aşamada modelin dosya yapısı, geometri yoğunluğu, dokuları ve yayınlanabilirliği iyileştirilir.",
  step3_li1: "Daha hafif 3D model yapısı",
  step3_li2: "Web uyumlu çıktı",
  step3_li3: "Mobil görüntüleme için optimizasyon",
  step3_li4: "Ürün sayfasına entegre edilebilir 3D varlık",
  step4_title: "Kalite Kontrolünden Geçer",
  step4_desc1: "IARONE’un farkı, üretilen modeli doğrudan yayınlamaması ve önce kalite kontrolünden geçirmesidir.",
  step4_desc2: "Sistem; modelin açılıp açılmadığını, dokuların doğru gelip gelmediğini, ürünün zemine oturup oturmadığını, dosyanın web ve AR için uygun olup olmadığını kontrol eder. Uygun olmayan çıktılar doğrudan publish edilmez.",
  step4_li1: "Model açılabilirlik kontrolü",
  step4_li2: "Doku ve materyal kontrolü",
  step4_li3: "Ölçek ve hizalama kontrolü",
  step4_li4: "Web / AR uygunluk kontrolü",
  step4_li5: "Publish öncesi kalite güveni",
  step5_title: "Publish Paketi Oluşturulur",
  step5_desc1: "Kalite kontrolü geçen ürün için yayınlanabilir 3D/AR paketi hazırlanır. Bu paket; GLB, USDZ, poster, thumbnail, metadata ve web entegrasyonu için gerekli çıktıları içerebilir.",
  step5_desc2: "Marka, ürünü kendi web sitesinde, ürün sayfasında veya paylaşılabilir bir IARONE sayfasında kullanabilir.",
  step5_li1: "GLB / USDZ çıktıları",
  step5_li2: "Poster ve thumbnail üretimi",
  step5_li3: "360° ürün görüntüleme",
  step5_li4: "AR deneyimine hazırlık",
  step5_li5: "Web sitesine eklenebilir publish paketi",
  bg_title: "Arka Planda Ne Olur?",
  bg_desc1: "Kullanıcı yalnızca ürününü yükler ve sonucu bekler. IARONE ise arka planda üretim sürecini kontrollü bir altyapı üzerinden yönetir.",
  bg_desc2: "Sistem; API, üretim kuyruğu, AI generation engine, kalite kontrol, asset registry ve publish akışından oluşur. Böylece süreç tek kişiye bağlı manuel bir hizmet gibi değil, modüler ve ölçeklenebilir bir teknoloji altyapısı gibi çalışır.",
  bg_flow_title: "Arka Plandaki Sistem Akışı",
  bg_flow_1: "1. Kullanıcı ürün fotoğrafını yükler",
  bg_flow_2: "2. API yeni üretim isteği oluşturur",
  bg_flow_3: "3. İşlem sıraya alınır (Queue)",
  bg_flow_4: "4. Generation engine modeli üretir",
  bg_flow_5: "5. Ham model optimize edilir",
  bg_flow_6: "6. Kalite kontrol (QA) yapılır",
  bg_flow_7: "7. Asset paketi hazırlanır",
  bg_flow_8: "8. Kullanıcı panelinde sonuç gösterilir",
  bg_flow_9: "9. Publish linki veya embed çıktısı oluşturulur",
  summary_badge: "Kısa Özet",
  summary_desc: "IARONE, ürün fotoğrafını alır; AI ile 3D modele dönüştürür, modeli web ve AR için optimize eder, kalite kontrolünden geçirir ve markanın e-ticaret sitesinde kullanabileceği yayınlanabilir bir 3D/AR pakete çevirir.",
  sum_1: "Fotoğraf yükle",
  sum_2: "3D üret",
  sum_3: "Optimize et",
  sum_4: "Kaliteyi kontrol et",
  sum_5: "Web & AR için yayınla",
  sum_cta: "Sistemi Ücretsiz Deneyin"
};

const market_tr = {
  badge_sector: "Sektörel Çözümler",
  hero_title: "Çözümler",
  hero_desc: "IARONE, farklı sektörlerdeki e-ticaret markalarının ürünlerini yalnızca fotoğrafla sergilemek yerine, müşteriye daha anlaşılır, etkileşimli ve güven veren 3D/AR deneyimleriyle sunmasını sağlar.",
  sec1_title: "Mobilya ve Dekorasyon",
  sec1_desc1: "Mobilya ürünlerinde müşterinin kararını en çok etkileyen unsurlar; boyut, hacim, renk, materyal ve ürünün ortam içindeki duruşudur.",
  sec1_desc2: "IARONE, koltuk, sandalye, masa, kitaplık, sehpa, dolap ve dekoratif ürünlerin 3D/AR deneyimine dönüştürülmesini sağlar. Böylece müşteri ürünü yalnızca fotoğraftan görmekle kalmaz; 360° inceleyebilir, detaylarını görebilir ve kendi yaşam alanında nasıl duracağını daha iyi hayal edebilir.",
  sec1_li1: "Koltuk, sandalye, masa ve sehpa ürünleri",
  sec1_li2: "Kitaplık, dolap ve raf sistemleri",
  sec1_li3: "Dekoratif objeler ve ev aksesuarları",
  sec1_li4: "AR ile ortamda ürün yerleştirme",
  sec1_li5: "Ürün sayfasında 360° görüntüleme",
  sec2_title: "Ayakkabı ve Moda Ürünleri",
  sec2_desc1: "Ayakkabı ve moda ürünlerinde müşterinin ürünü farklı açılardan görmesi, detayları incelemesi ve ürün formunu daha iyi anlaması satın alma kararını güçlendirir.",
  sec2_desc2: "IARONE, ayakkabı, çanta, aksesuar ve premium moda ürünlerini 3D görüntülemeye uygun hale getirerek markaların ürün sayfalarında daha etkileşimli bir deneyim sunmasına yardımcı olur.",
  sec2_li1: "Spor ayakkabı ve günlük ayakkabılar",
  sec2_li2: "Çanta ve deri aksesuarlar",
  sec2_li3: "Premium moda ürünleri",
  sec2_li4: "Ürün detaylarının 360° gösterimi",
  sec2_li5: "Koleksiyon bazlı ürün deneyimleri",
  sec3_title: "Saat ve Mücevher",
  sec3_desc1: "Saat ve mücevher gibi premium ürünlerde detay, malzeme hissi ve güven çok önemlidir. Müşteri ürünü ne kadar yakından ve net incelerse satın alma kararı o kadar güçlenir.",
  sec3_desc2: "IARONE, saat, yüzük, kolye, bileklik ve benzeri ürünlerin dijital ortamda daha etkileyici şekilde sunulmasını sağlar. Ürünler 3D olarak incelenebilir, farklı açılardan görüntülenebilir ve web üzerinde daha premium bir deneyimle sergilenebilir.",
  sec3_li1: "Saat modelleri",
  sec3_li2: "Yüzük, kolye ve bileklikler",
  sec3_li3: "Mücevher koleksiyonları",
  sec3_li4: "Premium ürün detay gösterimi",
  sec3_li5: "Web üzerinde yüksek algılı ürün sunumu",
  sec4_title: "Aydınlatma ve Ev Aksesuarları",
  sec4_desc1: "Lamba, avize ve dekoratif aydınlatma ürünlerinde ürünün formu, boyutu ve mekân içindeki duruşu müşterinin kararını doğrudan etkiler.",
  sec4_desc2: "IARONE, aydınlatma ürünlerinin 3D ve AR deneyimlerine dönüştürülmesini sağlayarak müşterinin ürünü daha iyi anlamasına yardımcı olur. Böylece kullanıcı, ürünün yalnızca görselini değil, mekânla olan ilişkisini de değerlendirebilir.",
  sec4_li1: "Masa lambaları",
  sec4_li2: "Avize ve sarkıt aydınlatmalar",
  sec4_li3: "Dekoratif ışık ürünleri",
  sec4_li4: "Ev ve ofis aksesuarları",
  sec4_li5: "AR ile mekân içinde görüntüleme",
  sec5_title: "Elektronik Aksesuarlar ve Teknoloji Ürünleri",
  sec5_desc1: "Teknoloji ürünlerinde kullanıcılar ürünün tasarımını, bağlantı noktalarını, boyutunu ve kullanım detaylarını net şekilde görmek ister.",
  sec5_desc2: "IARONE, kulaklık, hoparlör, telefon aksesuarları, küçük elektronik ürünler ve teknoloji ekipmanları için 3D ürün deneyimi sunulmasını sağlar. Bu yapı, ürünün teknik ve fiziksel detaylarını daha anlaşılır hale getirir.",
  sec5_li1: "Kulaklık, hoparlör ve küçük elektronik ürünler",
  sec5_li2: "Telefon ve bilgisayar aksesuarları",
  sec5_li3: "Akıllı cihaz ekipmanları",
  sec5_li4: "Ürün detaylarının etkileşimli gösterimi",
  sec5_li5: "Web uyumlu 3D ürün sunumu",
  sec6_title: "Kozmetik, Ambalaj ve Premium Ürünler",
  sec6_desc1: "Ambalaj tasarımı güçlü olan ürünlerde 3D sunum, ürün algısını yükseltir ve markanın premium görünmesini sağlar.",
  sec6_desc2: "IARONE, parfüm şişesi, kozmetik ambalajı, kutulu ürünler ve özel tasarım paketlerin 3D olarak sergilenmasına yardımcı olur. Böylece marka, ürününü klasik fotoğraf sunumunun ötesine taşıyarak daha dikkat çekici bir deneyim oluşturabilir.",
  sec6_li1: "Parfüm ve kozmetik ambalajları",
  sec6_li2: "Premium kutulu ürünler",
  sec6_li3: "Hediye setleri",
  sec6_li4: "Ürün lansman görselleri",
  sec6_li5: "Etkileşimli ürün tanıtımları",
  sec7_title: "Farklı bir sektör mü?",
  sec7_desc: "Eğer ürün grubunuz bu listede yoksa, markanıza özel 3D modelleme olanakları hakkında konuşabiliriz.",
  sec7_cta: "Bizimle İletişime Geçin"
};

const how_it_works_en = {
  badge_flow: "Flow",
  hero_title: "How It Works?",
  hero_desc: "IARONE generates sales-ready 3D/AR assets that can be used on the web and in augmented reality, starting from a product photo. The brand simply uploads the product visual; the system manages the 3D production, optimization, quality control, and publishing processes in a single flow in the background.",
  step1_title: "Upload Product Photo",
  step1_desc1: "The brand uploads the product photo to the IARONE panel. Details such as product name, category, optional size information, or a reference object can be added.",
  step1_desc2: "The user does not need technical knowledge at this step. Blender, 3D modeling, or AR integration knowledge is not required.",
  step_highlights: "Highlights",
  step1_li1: "Product photo upload",
  step1_li2: "Category selection",
  step1_li3: "Adding size / reference info",
  step1_li4: "No-code, technically simple start",
  step2_title: "AI 3D Model Production Begins",
  step2_desc1: "The uploaded visual is transferred to IARONE's 3D production infrastructure. The system analyzes the product's form, volume, and basic geometry to initiate the 3D model production process.",
  step2_desc2: "The goal at this stage is not just to create a 3D file, but to produce a product asset suitable for e-commerce use.",
  step2_li1: "3D model generation from visual",
  step2_li2: "Extracting the product form",
  step2_li3: "Creating geometry and basic surface structure",
  step2_li4: "E-commerce focused 3D production flow",
  step3_title: "Model is Optimized for Web and E-commerce",
  step3_desc1: "The raw model produced by AI is not given directly to the customer. IARONE makes the model load faster on websites, easier to view on product pages, and smoother to run on mobile devices.",
  step3_desc2: "At this stage, the model's file structure, geometry density, textures, and publishability are improved.",
  step3_li1: "Lighter 3D model structure",
  step3_li2: "Web compatible output",
  step3_li3: "Optimization for mobile viewing",
  step3_li4: "3D asset integratable into product pages",
  step4_title: "Passes Quality Control",
  step4_desc1: "The difference with IARONE is that it does not publish the produced model directly, but puts it through quality control first.",
  step4_desc2: "The system checks whether the model can be opened, if the textures are applied correctly, if the product sits properly on the ground, and if the file is suitable for web and AR. Unsuitable outputs are not published directly.",
  step4_li1: "Model openability check",
  step4_li2: "Texture and material check",
  step4_li3: "Scale and alignment check",
  step4_li4: "Web / AR suitability check",
  step4_li5: "Quality assurance before publishing",
  step5_title: "Publish Package is Created",
  step5_desc1: "A publishable 3D/AR package is prepared for the product that passes quality control. This package may include GLB, USDZ, poster, thumbnail, metadata, and necessary outputs for web integration.",
  step5_desc2: "The brand can use the product on its own website, product page, or a shareable IARONE page.",
  step5_li1: "GLB / USDZ outputs",
  step5_li2: "Poster and thumbnail production",
  step5_li3: "360° product viewing",
  step5_li4: "Preparation for AR experience",
  step5_li5: "Publish package attachable to websites",
  bg_title: "What Happens in the Background?",
  bg_desc1: "The user simply uploads their product and waits for the result. IARONE, on the other hand, manages the production process over a controlled infrastructure in the background.",
  bg_desc2: "The system consists of API, production queue, AI generation engine, quality control, asset registry, and publish flow. Thus, the process operates not as a manual service dependent on a single person, but as a modular and scalable technology infrastructure.",
  bg_flow_title: "Background System Flow",
  bg_flow_1: "1. User uploads product photo",
  bg_flow_2: "2. API creates a new production request",
  bg_flow_3: "3. Operation is queued (Queue)",
  bg_flow_4: "4. Generation engine produces the model",
  bg_flow_5: "5. Raw model is optimized",
  bg_flow_6: "6. Quality control (QA) is performed",
  bg_flow_7: "7. Asset package is prepared",
  bg_flow_8: "8. Result is displayed on user dashboard",
  bg_flow_9: "9. Publish link or embed output is generated",
  summary_badge: "Brief Summary",
  summary_desc: "IARONE takes the product photo, converts it into a 3D model with AI, optimizes the model for web and AR, runs it through quality control, and turns it into a publishable 3D/AR package that the brand can use on its e-commerce site.",
  sum_1: "Upload photo",
  sum_2: "Generate 3D",
  sum_3: "Optimize",
  sum_4: "Check quality",
  sum_5: "Publish for Web & AR",
  sum_cta: "Try the System for Free"
};

const market_en = {
  badge_sector: "Industry Solutions",
  hero_title: "Solutions",
  hero_desc: "IARONE enables e-commerce brands in various industries to present their products with clearer, interactive, and confidence-building 3D/AR experiences, rather than just displaying them with photos.",
  sec1_title: "Furniture and Decoration",
  sec1_desc1: "In furniture products, the elements that most affect the customer's decision are size, volume, color, material, and how the product stands in the environment.",
  sec1_desc2: "IARONE enables armchairs, chairs, tables, bookcases, coffee tables, cabinets, and decorative products to be transformed into 3D/AR experiences. Thus, the customer not only sees the product from a photo but can view it 360°, see its details, and better imagine how it will look in their own living space.",
  sec1_li1: "Armchairs, chairs, tables, and coffee tables",
  sec1_li2: "Bookcases, cabinets, and shelving systems",
  sec1_li3: "Decorative objects and home accessories",
  sec1_li4: "Product placement in environment with AR",
  sec1_li5: "360° viewing on the product page",
  sec2_title: "Footwear and Fashion Products",
  sec2_desc1: "In footwear and fashion products, seeing the product from different angles, examining details, and better understanding the product form strengthens the customer's purchasing decision.",
  sec2_desc2: "IARONE helps brands offer a more interactive experience on product pages by making shoes, bags, accessories, and premium fashion products suitable for 3D viewing.",
  sec2_li1: "Sneakers and casual shoes",
  sec2_li2: "Bags and leather accessories",
  sec2_li3: "Premium fashion products",
  sec2_li4: "360° display of product details",
  sec2_li5: "Collection-based product experiences",
  sec3_title: "Watches and Jewelry",
  sec3_desc1: "In premium products such as watches and jewelry, detail, material feel, and trust are very important. The closer and clearer the customer examines the product, the stronger the purchasing decision becomes.",
  sec3_desc2: "IARONE ensures that products such as watches, rings, necklaces, bracelets, and similar items are presented more impressively in the digital environment. Products can be examined in 3D, viewed from different angles, and displayed with a more premium experience on the web.",
  sec3_li1: "Watch models",
  sec3_li2: "Rings, necklaces, and bracelets",
  sec3_li3: "Jewelry collections",
  sec3_li4: "Premium product detail display",
  sec3_li5: "High-perception product presentation on the web",
  sec4_title: "Lighting and Home Accessories",
  sec4_desc1: "In lamps, chandeliers, and decorative lighting products, the form, size, and stance of the product within the space directly affect the customer's decision.",
  sec4_desc2: "IARONE helps the customer better understand the product by enabling lighting products to be transformed into 3D and AR experiences. Thus, the user can evaluate not only the visual of the product but also its relationship with the space.",
  sec4_li1: "Table lamps",
  sec4_li2: "Chandeliers and pendant lights",
  sec4_li3: "Decorative lighting products",
  sec4_li4: "Home and office accessories",
  sec4_li5: "Viewing within the space via AR",
  sec5_title: "Electronic Accessories and Tech Products",
  sec5_desc1: "In technology products, users want to clearly see the design, connection ports, size, and usage details of the product.",
  sec5_desc2: "IARONE provides a 3D product experience for headphones, speakers, phone accessories, small electronic devices, and tech equipment. This structure makes the technical and physical details of the product more understandable.",
  sec5_li1: "Headphones, speakers, and small electronics",
  sec5_li2: "Phone and computer accessories",
  sec5_li3: "Smart device equipment",
  sec5_li4: "Interactive display of product details",
  sec5_li5: "Web-compatible 3D product presentation",
  sec6_title: "Cosmetics, Packaging, and Premium Products",
  sec6_desc1: "For products with strong packaging design, 3D presentation elevates the product perception and makes the brand look premium.",
  sec6_desc2: "IARONE helps showcase perfume bottles, cosmetic packaging, boxed products, and custom-designed packages in 3D. This way, the brand can take its product beyond classic photo presentation and create a more striking experience.",
  sec6_li1: "Perfume and cosmetic packaging",
  sec6_li2: "Premium boxed products",
  sec6_li3: "Gift sets",
  sec6_li4: "Product launch visuals",
  sec6_li5: "Interactive product promotions",
  sec7_title: "Different industry?",
  sec7_desc: "If your product group is not on this list, we can discuss custom 3D modeling possibilities for your brand.",
  sec7_cta: "Contact Us"
};

const how_it_works_ar = {
  badge_flow: "التدفق",
  hero_title: "كيف يعمل؟",
  hero_desc: "تقوم IARONE بإنشاء أصول ثلاثية الأبعاد / واقع معزز جاهزة للمبيعات يمكن استخدامها على الويب والواقع المعزز، بدءًا من صورة المنتج. تقوم العلامة التجارية ببساطة بتحميل صورة المنتج؛ ويدير النظام عمليات الإنتاج والتحسين ومراقبة الجودة والنشر ثلاثية الأبعاد في تدفق واحد في الخلفية.",
  step1_title: "تحميل صورة المنتج",
  step1_desc1: "تقوم العلامة التجارية بتحميل صورة المنتج إلى لوحة IARONE. يمكن إضافة تفاصيل مثل اسم المنتج والفئة ومعلومات الحجم الاختيارية أو كائن مرجعي.",
  step1_desc2: "لا يحتاج المستخدم إلى معرفة فنية في هذه الخطوة. لا يلزم وجود معرفة ببرنامج Blender أو النمذجة ثلاثية الأبعاد أو تكامل الواقع المعزز.",
  step_highlights: "أبرز الميزات",
  step1_li1: "تحميل صورة المنتج",
  step1_li2: "اختيار الفئة",
  step1_li3: "إضافة الحجم / المعلومات المرجعية",
  step1_li4: "بداية بسيطة تقنيًا بدون كود",
  step2_title: "يبدأ إنتاج نموذج ثلاثي الأبعاد بالذكاء الاصطناعي",
  step2_desc1: "يتم نقل الصورة التي تم تحميلها إلى البنية التحتية للإنتاج ثلاثي الأبعاد لـ IARONE. يقوم النظام بتحليل شكل المنتج وحجمه وهندسته الأساسية لبدء عملية إنتاج النموذج ثلاثي الأبعاد.",
  step2_desc2: "الهدف في هذه المرحلة ليس مجرد إنشاء ملف ثلاثي الأبعاد، ولكن إنتاج أصل منتج مناسب لاستخدام التجارة الإلكترونية.",
  step2_li1: "توليد نموذج ثلاثي الأبعاد من الصورة",
  step2_li2: "استخراج شكل المنتج",
  step2_li3: "إنشاء الهندسة والبنية الأساسية للسطح",
  step2_li4: "تدفق إنتاج ثلاثي الأبعاد يركز على التجارة الإلكترونية",
  step3_title: "تم تحسين النموذج للويب والتجارة الإلكترونية",
  step3_desc1: "النموذج الخام المنتج بواسطة الذكاء الاصطناعي لا يُعطى للعميل مباشرة. تجعل IARONE تحميل النموذج أسرع على مواقع الويب، وأسهل للعرض على صفحات المنتجات، وأكثر سلاسة في التشغيل على الأجهزة المحمولة.",
  step3_desc2: "في هذه المرحلة، يتم تحسين بنية ملف النموذج، وكثافة الهندسة، والقوام، وقابلية النشر.",
  step3_li1: "هيكل نموذج ثلاثي الأبعاد أخف وزناً",
  step3_li2: "إخراج متوافق مع الويب",
  step3_li3: "التحسين لعرض الهاتف المحمول",
  step3_li4: "أصل ثلاثي الأبعاد قابل للدمج في صفحات المنتجات",
  step4_title: "يمر بمراقبة الجودة",
  step4_desc1: "الفرق مع IARONE هو أنها لا تنشر النموذج المُنتج مباشرة، بل تضعه في مراقبة الجودة أولاً.",
  step4_desc2: "يتحقق النظام مما إذا كان يمكن فتح النموذج، وما إذا تم تطبيق القوام بشكل صحيح، وما إذا كان المنتج موضوعًا بشكل صحيح على الأرض، وما إذا كان الملف مناسبًا للويب والواقع المعزز. المخرجات غير المناسبة لا يتم نشرها مباشرة.",
  step4_li1: "التحقق من إمكانية فتح النموذج",
  step4_li2: "التحقق من الملمس والمواد",
  step4_li3: "التحقق من المقياس والمحاذاة",
  step4_li4: "التحقق من ملاءمة الويب / الواقع المعزز",
  step4_li5: "ضمان الجودة قبل النشر",
  step5_title: "تم إنشاء حزمة النشر",
  step5_desc1: "يتم إعداد حزمة ثلاثية الأبعاد / واقع معزز قابلة للنشر للمنتج الذي يجتاز مراقبة الجودة. قد تتضمن هذه الحزمة GLB و USDZ وملصق وصورة مصغرة وبيانات وصفية والمخرجات الضرورية لتكامل الويب.",
  step5_desc2: "يمكن للعلامة التجارية استخدام المنتج على موقع الويب الخاص بها، أو صفحة المنتج، أو صفحة IARONE قابلة للمشاركة.",
  step5_li1: "مخرجات GLB / USDZ",
  step5_li2: "إنتاج الملصقات والصور المصغرة",
  step5_li3: "عرض المنتج 360 درجة",
  step5_li4: "الاستعداد لتجربة الواقع المعزز",
  step5_li5: "حزمة نشر قابلة للإرفاق بمواقع الويب",
  bg_title: "ماذا يحدث في الخلفية؟",
  bg_desc1: "يقوم المستخدم ببساطة بتحميل منتجه وينتظر النتيجة. IARONE، من ناحية أخرى، تدير عملية الإنتاج عبر بنية تحتية خاضعة للرقابة في الخلفية.",
  bg_desc2: "يتكون النظام من واجهة برمجة التطبيقات، وقائمة انتظار الإنتاج، ومحرك توليد الذكاء الاصطناعي، ومراقبة الجودة، وسجل الأصول، وتدفق النشر. وبالتالي، لا تعمل العملية كخدمة يدوية تعتمد على شخص واحد، ولكن كبنية تحتية تكنولوجية معيارية وقابلة للتطوير.",
  bg_flow_title: "تدفق نظام الخلفية",
  bg_flow_1: "1. المستخدم يحمل صورة المنتج",
  bg_flow_2: "2. واجهة برمجة التطبيقات تنشئ طلب إنتاج جديد",
  bg_flow_3: "3. العملية في قائمة الانتظار (Queue)",
  bg_flow_4: "4. محرك التوليد ينتج النموذج",
  bg_flow_5: "5. تم تحسين النموذج الخام",
  bg_flow_6: "6. يتم إجراء مراقبة الجودة (QA)",
  bg_flow_7: "7. تم إعداد حزمة الأصول",
  bg_flow_8: "8. يتم عرض النتيجة على لوحة تحكم المستخدم",
  bg_flow_9: "9. يتم إنشاء رابط النشر أو إخراج التضمين",
  summary_badge: "ملخص موجز",
  summary_desc: "تأخذ IARONE صورة المنتج، وتحولها إلى نموذج ثلاثي الأبعاد بالذكاء الاصطناعي، وتحسن النموذج للويب والواقع المعزز، وتمرره عبر مراقبة الجودة، وتحوله إلى حزمة قابلة للنشر ثلاثية الأبعاد / واقع معزز يمكن للعلامة التجارية استخدامها على موقع التجارة الإلكترونية الخاص بها.",
  sum_1: "تحميل الصورة",
  sum_2: "توليد 3D",
  sum_3: "تحسين",
  sum_4: "التحقق من الجودة",
  sum_5: "النشر للويب والواقع المعزز",
  sum_cta: "جرب النظام مجانًا"
};

const market_ar = {
  badge_sector: "حلول الصناعة",
  hero_title: "حلول",
  hero_desc: "تُمكّن IARONE العلامات التجارية للتجارة الإلكترونية في مختلف الصناعات من تقديم منتجاتها بتجارب ثلاثية الأبعاد / واقع معزز أكثر وضوحًا وتفاعلية وبناءً للثقة، بدلاً من مجرد عرضها بالصور.",
  sec1_title: "الأثاث والديكور",
  sec1_desc1: "في منتجات الأثاث، العناصر التي تؤثر أكثر على قرار العميل هي الحجم والحجم واللون والمواد وكيف يقف المنتج في البيئة.",
  sec1_desc2: "تتيح IARONE تحويل الكراسي ذات الذراعين والكراسي والطاولات وخزائن الكتب وطاولات القهوة والخزائن ومنتجات الديكور إلى تجارب ثلاثية الأبعاد / واقع معزز. وبالتالي، لا يرى العميل المنتج من صورة فحسب، بل يمكنه عرضه بزاوية 360 درجة، ورؤية تفاصيله، وتخيل كيف سيبدو في مساحة المعيشة الخاصة به.",
  sec1_li1: "كراسي وكراسي وطاولات وطاولات قهوة",
  sec1_li2: "خزائن الكتب والخزائن وأنظمة الرفوف",
  sec1_li3: "كائنات زخرفية وإكسسوارات منزلية",
  sec1_li4: "وضع المنتج في البيئة باستخدام الواقع المعزز",
  sec1_li5: "عرض 360 درجة على صفحة المنتج",
  sec2_title: "الأحذية ومنتجات الموضة",
  sec2_desc1: "في منتجات الأحذية والموضة، رؤية المنتج من زوايا مختلفة، ودراسة التفاصيل، وفهم شكل المنتج بشكل أفضل يعزز قرار الشراء لدى العميل.",
  sec2_desc2: "تساعد IARONE العلامات التجارية على تقديم تجربة أكثر تفاعلية على صفحات المنتجات من خلال جعل الأحذية والحقائب والإكسسوارات ومنتجات الموضة الممتازة مناسبة للعرض ثلاثي الأبعاد.",
  sec2_li1: "أحذية رياضية وأحذية غير رسمية",
  sec2_li2: "حقائب واكسسوارات جلدية",
  sec2_li3: "منتجات أزياء متميزة",
  sec2_li4: "عرض 360 درجة لتفاصيل المنتج",
  sec2_li5: "تجارب المنتجات القائمة على المجموعات",
  sec3_title: "الساعات والمجوهرات",
  sec3_desc1: "في المنتجات المتميزة مثل الساعات والمجوهرات، فإن التفاصيل وإحساس المواد والثقة مهمة جدًا. كلما اقترب العميل من فحص المنتج وأصبح أكثر وضوحًا، أصبح قرار الشراء أقوى.",
  sec3_desc2: "تضمن IARONE عرض منتجات مثل الساعات والخواتم والقلائد والأساور والعناصر المماثلة بشكل أكثر إثارة للإعجاب في البيئة الرقمية. يمكن فحص المنتجات بأبعاد ثلاثية، ومشاهدتها من زوايا مختلفة، وعرضها بتجربة أكثر تميزًا على الويب.",
  sec3_li1: "نماذج الساعات",
  sec3_li2: "خواتم وقلائد وأساور",
  sec3_li3: "مجموعات المجوهرات",
  sec3_li4: "عرض تفاصيل المنتج الممتاز",
  sec3_li5: "تقديم منتج عالي الإدراك على الويب",
  sec4_title: "الإضاءة والإكسسوارات المنزلية",
  sec4_desc1: "في المصابيح والثريات ومنتجات الإضاءة الزخرفية، يؤثر شكل وحجم وموقف المنتج داخل المساحة بشكل مباشر على قرار العميل.",
  sec4_desc2: "تساعد IARONE العميل على فهم المنتج بشكل أفضل من خلال تمكين تحويل منتجات الإضاءة إلى تجارب ثلاثية الأبعاد والواقع المعزز. وبالتالي، يمكن للمستخدم تقييم ليس فقط الجانب المرئي للمنتج ولكن أيضًا علاقته بالمساحة.",
  sec4_li1: "مصابيح الطاولة",
  sec4_li2: "ثريات وأضواء متدلية",
  sec4_li3: "منتجات الإضاءة الزخرفية",
  sec4_li4: "اكسسوارات المنزل والمكتب",
  sec4_li5: "المشاهدة داخل المساحة عبر الواقع المعزز",
  sec5_title: "الملحقات الإلكترونية والمنتجات التقنية",
  sec5_desc1: "في منتجات التكنولوجيا، يريد المستخدمون رؤية التصميم ومنافذ الاتصال والحجم وتفاصيل الاستخدام الخاصة بالمنتج بوضوح.",
  sec5_desc2: "توفر IARONE تجربة منتج ثلاثية الأبعاد لسماعات الرأس ومكبرات الصوت وملحقات الهاتف والأجهزة الإلكترونية الصغيرة والمعدات التقنية. هذه البنية تجعل التفاصيل التقنية والمادية للمنتج أكثر قابلية للفهم.",
  sec5_li1: "سماعات رأس ومكبرات صوت وإلكترونيات صغيرة",
  sec5_li2: "ملحقات الهاتف والكمبيوتر",
  sec5_li3: "معدات الأجهزة الذكية",
  sec5_li4: "عرض تفاعلي لتفاصيل المنتج",
  sec5_li5: "عرض منتج ثلاثي الأبعاد متوافق مع الويب",
  sec6_title: "مستحضرات التجميل والتغليف والمنتجات المتميزة",
  sec6_desc1: "بالنسبة للمنتجات ذات تصميم التغليف القوي، فإن العرض ثلاثي الأبعاد يرفع من إدراك المنتج ويجعل العلامة التجارية تبدو متميزة.",
  sec6_desc2: "تساعد IARONE في عرض زجاجات العطور وتغليف مستحضرات التجميل والمنتجات المعبأة في صناديق والحزم المصممة خصيصًا في شكل ثلاثي الأبعاد. بهذه الطريقة، يمكن للعلامة التجارية أن تأخذ منتجها إلى ما هو أبعد من عرض الصور الكلاسيكي وإنشاء تجربة أكثر لفتًا للانتباه.",
  sec6_li1: "عطور وتغليف مستحضرات التجميل",
  sec6_li2: "المنتجات المتميزة المعبأة",
  sec6_li3: "مجموعات الهدايا",
  sec6_li4: "مرئيات إطلاق المنتج",
  sec6_li5: "عروض المنتجات التفاعلية",
  sec7_title: "صناعة مختلفة؟",
  sec7_desc: "إذا لم تكن مجموعة منتجاتك مدرجة في هذه القائمة، فيمكننا مناقشة إمكانيات النمذجة ثلاثية الأبعاد المخصصة لعلامتك التجارية.",
  sec7_cta: "اتصل بنا"
};

let content = fs.readFileSync('i18n.js', 'utf8');

function inject(langCode, hwObj, mkObj) {
    const hwStr = JSON.stringify(hwObj, null, 6);
    const mkStr = JSON.stringify(mkObj, null, 6);
    const hwInner = hwStr.substring(1, hwStr.length - 1);
    const mkInner = mkStr.substring(1, mkStr.length - 1);
    
    // find langCode: {
    const regex = new RegExp(`(${langCode}:\\s*\\{)`);
    const match = content.match(regex);
    if (match) {
        const replacement = `\n    how_it_works: {${hwInner}},\n    market: {${mkInner}},\n`;
        content = content.replace(regex, `$1${replacement}`);
    }
}

inject('tr', how_it_works_tr, market_tr);
inject('en', how_it_works_en, market_en);
if (content.includes('ar: {')) {
    inject('ar', how_it_works_ar, market_ar);
}

fs.writeFileSync('i18n.js', content, 'utf8');
console.log('Injected hw and market translations.');
